### PR TITLE
Give the named branches token write access to push.

### PR DESCRIPTION
**Pull request by Julian**
And limit how much we fetch so we don't wait ages.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks

**Comment by mattip** [comment]
... and it is green. Maybe update the named-branches README to reflect this? Thanks for the quick response.

**Comment by Julian** [comment]
> Maybe update the named-branches README to reflect this? 
Just did!

And my pleasure, does seem to work at least for a few of the recent commits! Hooray.

**Comment by Julian** [comment]
Ah hrm wait, not sure yet actually, it reports 8e7f30b0a87 as being made on main, but that shouldn't be the case I think... Going to keep an eye out, I think maybe there is/was a change in GHActions having to do with detached head that might be affecting things.

**Pull request merged**
