### PR TITLE
fix cffi*.dist-info directory name

### PR DESCRIPTION
**Pull request by mgorny**
Fix the `cffi.1.16.0.dist-info` to be `cffi-1.16.0.dist-info`, in order to make it possible to find it via importlib.metadata.

### CODE REVIEW

**Comment by mattip** [comment]
Thanks. Shouldn't this target py3.9?

**Comment by mgorny** [comment]
Ah, indeed. Sorry, I've checked `py3.9` but forgot to pull.

**Comment by cfbolz** [comment]
@mgorny if we now get PRs from you, that's probably worth the move alone ;-)

**Comment by mgorny** [comment]
Thanks!

**Comment by mgorny** [comment]
```pytb
$ ./pypy3.10 -c 'from importlib.metadata import version; print(version("cffi"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pypy-c-jit-108164-1eb2cae16d80-linux64/lib/pypy3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy-c-jit-108164-1eb2cae16d80-linux64/lib/pypy3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pypy-c-jit-108164-1eb2cae16d80-linux64/lib/pypy3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for cffi
```

**Comment by mgorny** [comment]
(I've hit it in the whild while running the test suite for https://pypi.org/project/Chameleon/)

**Comment by mattip** [comment]
Thanks @mgorny

**Comment by mgorny** [comment]
Thanks! Do you need me to do anything about py3.10 now or will you handle merging the change to it?

**Pull request merged**
