### PR TITLE
Switch to xz compression

### PR DESCRIPTION
**Pull request by thesamesam**
xz produces smaller tarballs and is preferred to bzip2 nowadays.

### CODE REVIEW

**Comment by thesamesam** [comment]
cc @mattip @mgorny 

I need to figure out how to test this properly though.

**Comment by mattip** [comment]
Hmm. The tarballs are used in the [setup-python github action](https://github.com/actions/setup-python), the filename is specified in the [`versions.json`](https://github.com/pypy/pypy/blob/main/pypy/tool/release/versions.json). The tarball is extracted [here](https://github.com/actions/setup-python/blob/e9d6f990972a57673cdb72ec29e19d42ba28880f/src/install-pypy.ts#L78) using `tool-cache.extractTar` from [tool-cache](https://github.com/actions/toolkit/tree/main/packages/tool-cache). Can that handle xz files?

**Comment by thesamesam** [comment]
> Is the compressed tar.xz file much smaller than the tar.bz2?

For `pypy3.10-v7.3.15-src.tar` (source) with default `xz` settings:
```
-rw------- 1 sam  sam 115M Jan 15 16:23 pypy3.10-v7.3.15-src.tar
-rw-rw-r-- 1 sam sam  23M Jan 15 16:23 pypy3.10-v7.3.15-src.tar.bz2
-rw------- 1 sam sam 18M Jan 15 16:23 pypy3.10-v7.3.15-src.tar.xz
```

For `pypy3.10-v7.3.15-linux64.tar.bz2` (binary) with default `xz` settings:
```
-rw-r--r-- 1 sam sam 136M Jan 15 06:37 pypy3.10-v7.3.15-linux64.tar
-rw-r--r-- 1 sam sam  32M Jan 15 06:37 pypy3.10-v7.3.15-linux64.tar.bz2
-rw-r--r-- 1 sam sam 25M Jan 15 06:37 pypy3.10-v7.3.15-linux64.tar.xz
```

I didn't mess with options to try get it smaller as I figured it's pretty much a free improvement as it is. I know it's not a _huge_ delta though.

> Hmm. The tarballs are used in the [setup-python github action](https://github.com/actions/setup-python), the filename is specified in the [`versions.json`](https://github.com/pypy/pypy/blob/main/pypy/tool/release/versions.json?rgh-link-date=2024-01-17T13%3A55%3A24Z). The tarball is extracted [here](https://github.com/actions/setup-python/blob/e9d6f990972a57673cdb72ec29e19d42ba28880f/src/install-pypy.ts#L78) using `tool-cache.extractTar` from [tool-cache](https://github.com/actions/toolkit/tree/main/packages/tool-cache?rgh-link-date=2024-01-17T13%3A55%3A24Z). Can that handle xz files?

Good point! I'll check this. CPython is distributed partly with `.tar.xz` so I suspect it's fine but I'll investigate.

**Comment by thesamesam** [comment]
I'll close this for now until I think I can come back to this & check the Action stuff, as I don't want to leave it lingering, as I sometimes have a tendency to do. Thanks!

**Pull request closed without merging**
