### PR TITLE
avoid keeping a ref to scope_w values while running self.behaviour

### LINKED ISSUE #5075: gc.get_referrers returns an extra redundant tuple
```python
import gc

class Ham:
    pass

def main():
    h = Ham()
    print(gc.get_referrers(h))

main()
```

prints:

```sh
pypy3 demo.py                      
[<frame at 0x00007be407e56020, file '/home/graingert/projects/anyio/demo.py', line 8, code main>, (<__main__.Ham object at 0x00007be407bbf440>,)]
```

I think the extra tuple is this `args_w` here: https://github.com/pypy/pypy/blob/72e9257dde455ca17884b409b62c9088508b633f/pypy/module/gc/referents.py#L134

I think it should be dropped from the returned list

### PR DESCRIPTION
**Pull request by graingert**
Fixes #5075

### CODE REVIEW

**Comment by mattip** [comment]
Is there a test for this change?

**Comment by graingert** [comment]
I'll be trying another approach shortly and will write a test

**Comment by mattip** [comment]
Any progress here? Need any help?

**Comment by graingert** [comment]
I don't think this approach is viable, and I'm distracted looking at other things. Will get back to this bug soon

**Pull request closed without merging**
