### PR TITLE
 revert 6906755 and skip untranslated tests 

### PR DESCRIPTION
**Pull request by mattip**
fixes some untranslated tests

### CODE REVIEW

**Comment by mattip** [comment]
cc @olliemath

**Comment by mattip** [comment]
Closes #4836

**Comment by olliemath** [comment]
Nice, thanks for this - I've been thinking on it this week. My conclusion was that it would actually be more consistent to raise a ValueError for all instances of `cast(lltype.UniChar, -1)` (regardless of platform).

This might break some very niche use-cases, but already this functionality isn't being used during pypy translation. And the bonus is that users don't have to worry about `sys.maxunicode` or `sys.executable` to know whether this operation is valid.

Happy to defer that to a future pull request.

**Comment by mattip** [comment]
It seems like such a niche use case that whatever we choose to do should be OK. There is the small issue that PyPy2 cannot index this array
```
array.array('u' , array.array("I", (0xffffffff,)).tostring())
```

where CPython2 can

**Pull request merged**
